### ISSUE TITLE
Not working with Kibana 5.5.0 version 

### ISSUE THREAD

**Issue by source-ram** [nreese/kibana-time-plugin#17]
Not working with Kibana 5.5.0 version

**Comment by nreese** [comment]
5.5 is not currently supported

**Comment by nreese** [comment]
Checkout branch 5.5 and let me know if you have any problems

**Comment by sreejithps303** [comment]
@nreese tried with 5.5 branch and still not showing any time widget visualization

**Comment by nreese** [comment]
Are there any errors in the kibana logs or browser console?

**Comment by sreejithps303** [comment]
@nreese  getting below error in kibana screen

Uncaught TypeError: Cannot read property 'get' of undefined (http://xx.xx.xx.xx/bundles/kibana.bundle.js?v=15382:262)
Version: 5.5.0
Build: 15382

Error: Uncaught TypeError: Cannot read property 'get' of undefined (http://xx.xx.xx.xx/bundles/kibana.bundle.js?v=15382:262)
    at window.onerror (http://xx.xx.xx.xx/bundles/commons.bundle.js?v=15382:90:21917)

**Comment by nreese** [comment]
That does not provide much information. Are you trying to create a new Time Visualization or do you have existing Time Visualizations?

**Comment by sreejithps303** [comment]
@nreese this error is coming in the first place when i am opening kibana URL. It is not loading anything else just this error on the screeen

**Comment by sasauz** [comment]
I have an error at the start of kibana. Hier is logs

`FATAL { Error: Optimizations failure.

    ERROR in ./plugins/kibana-time-plugin-5.5/public/time.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/local/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugin-5.5/                                                                                                public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css in /usr/local/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-plu                                                                                                gin-5.5/public
     @ ./plugins/kibana-time-plugin-5.5/public/time.js 11:0-101

    ERROR in ./plugins/kibana-time-plugin-5.5/public/time.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/local/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugin-5.5/                                                                                                public/bower_components/bootstrap-addons/dist/js/bootstrap-addons.js in /usr/local/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugi                                                                                                n-5.5/public
     @ ./plugins/kibana-time-plugin-5.5/public/time.js 13:0-99

    at Object.exports.create (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/boom/lib/index.js:21:17)
    at FsOptimizer.failedStatsToError (/usr/local/kibana/kibana-5.5.0-linux-x86_64/src/optimize/base_optimizer.js:233:27)
    at /usr/local/kibana/kibana-5.5.0-linux-x86_64/src/optimize/fs_optimizer.js:33:30
    at Compiler.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compiler.js:181:13)
    at /usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)
    at Compilation.applyPluginsAsync (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Compilation.applyPluginsAsync (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/extract-text-webpack-plugin/index.js:279:5)
  cause:
   { Error: Optimizations failure.

       ERROR in ./plugins/kibana-time-plugin-5.5/public/time.js
       Module not found: Error: Cannot resolve 'file' or 'directory' /usr/local/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugin-5                                                                                                .5/public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css in /usr/local/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-                                                                                                plugin-5.5/public
        @ ./plugins/kibana-time-plugin-5.5/public/time.js 11:0-101

       ERROR in ./plugins/kibana-time-plugin-5.5/public/time.js
       Module not found: Error: Cannot resolve 'file' or 'directory' /usr/local/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugin-5                                                                                                .5/public/bower_components/bootstrap-addons/dist/js/bootstrap-addons.js in /usr/local/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-pl                                                                                                ugin-5.5/public
        @ ./plugins/kibana-time-plugin-5.5/public/time.js 13:0-99

       at Object.exports.create (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/boom/lib/index.js:21:17)
       at FsOptimizer.failedStatsToError (/usr/local/kibana/kibana-5.5.0-linux-x86_64/src/optimize/base_optimizer.js:233:27)
       at /usr/local/kibana/kibana-5.5.0-linux-x86_64/src/optimize/fs_optimizer.js:33:30
       at Compiler.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compiler.js:181:13)
       at /usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compiler.js:403:12
       at Compiler.next (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:67:11)
       at Compiler.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/CachePlugin.js:40:4)
       at Compiler.applyPluginsAsync (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:71:13)
       at Compiler.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compiler.js:400:9)
       at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compilation.js:577:13)
       at Compilation.applyPluginsAsync (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:60:69)
       at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compilation.js:572:10)
       at Compilation.next (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:67:11)
       at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)
       at Compilation.applyPluginsAsync (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:71:13)
       at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compilation.js:567:9)
       at Compilation.next (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:67:11)
       at ExtractTextPlugin.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/extract-text-webpack-plugin/index.js:303:4)
       at Compilation.applyPluginsAsync (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:71:13)
       at Compilation.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/webpack/lib/Compilation.js:563:8)
       at Compilation.next (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/tapable/lib/Tapable.js:67:11)
       at ExtractTextPlugin.<anonymous> (/usr/local/kibana/kibana-5.5.0-linux-x86_64/node_modules/extract-text-webpack-plugin/index.js:279:5)
     data: { errors: [Object], warnings: [], publicPath: '/bundles/' },
     isBoom: true,
     isServer: true,
     output: { statusCode: 500, payload: [Object], headers: {} },
     reformat: [Function] },
  isOperational: true,
  data:
   { errors:
      [ './plugins/kibana-time-plugin-5.5/public/time.js\nModule not found: Error: Cannot resolve \'file\' or \'directory\' /usr/local/kibana                                                                                                /kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugin-5.5/public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css in /usr/loca                                                                                                l/kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugin-5.5/public\n @ ./plugins/kibana-time-plugin-5.5/public/time.js 11:0-101',
        './plugins/kibana-time-plugin-5.5/public/time.js\nModule not found: Error: Cannot resolve \'file\' or \'directory\' /usr/local/kibana                                                                                                /kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugin-5.5/public/bower_components/bootstrap-addons/dist/js/bootstrap-addons.js in /usr/local/                                                                                                kibana/kibana-5.5.0-linux-x86_64/plugins/kibana-time-plugin-5.5/public\n @ ./plugins/kibana-time-plugin-5.5/public/time.js 13:0-99' ],
     warnings: [],
     publicPath: '/bundles/' },
  isBoom: true,
  isServer: true,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function] }
`

**Comment by sasauz** [comment]
I've solved it. 
Solution:
1. rename **plugins/kibana-time-plugin-5.5** to **plugins/kibana-time-plugin**
2. add
      -plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/js/bootstrap-addons.js
      -plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css

Thank you! Everything works!

**Comment by sasauz** [comment]
one more point: I have changed **"version": "5.5.1"** to **"version": "5.5.0"** in package.json file

@sreejithps303 may be it can help you

**Comment by TaurusD** [comment]
@nreese Hi, I'm using kibana 5.5.1 and I got this error: 

> Uncaught TypeError: Cannot read property 'get' of undefined (http://localhost:5601/bundles/kibana.bundle.js?v=15405:155)

where 

> Version: 5.5.1
> Build: 15405


> Error: Uncaught TypeError: Cannot read property 'get' of undefined (http://localhost:5601/bundles/kibana.bundle.js?v=15405:155)
>     at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15405:76:8884)

**Comment by TaurusD** [comment]
and when I remove the plugin, everything back to normal
Same issue occurred on v5.5.0

**Comment by TaurusD** [comment]
@sasauz Hi, I've tried both 5.5.0 and 5.5.1 and errored. 
I hope to try your solution by adding bootstrap, but I can't find a folder called `bower_components`. 

Also could you please tell me where to find the proper source of `bootstrap-addons.js` and `bootstrap-addons.css` ? Thank you!

**Comment by sasauz** [comment]
@TaurusD I've create the bower_component folder manualy and copy everythink from here: https://github.com/nreese/kibana-time-plugin/tree/4.x/public/lib/bootstrap-addons

At the end it should look like this:
-plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/js/bootstrap-addons.js
-plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css

**Comment by sasauz** [comment]
If you have bower and it works in your infrastructure (Unfortunately it doesn't work in my environmental), you can use this
`cd KIBANA_HOME/plugins/kibana-time-plugin`
`bower install`

bower will create the bower_components folder automaticaly and will import all dependencies

**Comment by TaurusD** [comment]
@sasauz So can I say the failure point is on `bootstrap-addons.css` and I should move it to js folder to solve the problem?

**Comment by sasauz** [comment]
@TaurusD do you use this repository: https://github.com/nreese/kibana-time-plugin/tree/5.5

**Comment by sasauz** [comment]
> @sasauz So can I say the failure point is on bootstrap-addons.css and I should move it to js folder to solve the problem?

Sorry it was copy-paste failure. It should be 
`plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/css/bootstrap-addons.css`

**Comment by TaurusD** [comment]
@sasauz Yes I did. Cuz I noticed that this is the most updated version. I'm using kibana 5.5.1

**Comment by TaurusD** [comment]
@sasauz 
> Sorry it was copy-paste failure. It schould be
> plugins/kibana-time-plugin/public/bower_components/bootstrap-addons/dist/**css**/bootstrap-addons.css

Well, I copied `addons` from `https://github.com/nreese/bootstrap-addons/files/851515/bootstrap-addons.zip` when I `bower install` the plugin. And I also copied the css file to the js folder. 
Now I can enter KIBANA successfully. So it's hard to obvious where the problem is, but anyway, you helped me to solve it. 

Thank you!

**Comment by sasauz** [comment]
I'm glad to hear that. You are welcome!
